<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>
        <WindowsPackageType>None</WindowsPackageType>
        <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <NoWarn>$(NoWarn);MVVMTK0045</NoWarn>
        <RootNamespace>Taskloom</RootNamespace>
        <ApplicationIcon>Assets\Icons\Taskloom.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Assets\Localization\**\*.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Data\Sql\**\*.sql">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Assets\Icons\**\*.ico">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Dapper" Version="2.1.66" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.4" />
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />
        <PackageReference Include="TagLibSharp" Version="2.3.0" />
    </ItemGroup>

</Project>
